"""TradeMetrics — a portfolio-analytics engine validated on synthetic data.

Modules
-------
loaders     CSV loading and trade-log cleaning
fifo        Long/short FIFO position matching with commission-adjusted P&L
metrics     Risk-adjusted performance metrics (Sharpe with Lo CI, Sortino, VaR, drawdown)
benchmark   CAPM alpha/beta against benchmark series
attribution Realised P&L attribution by ticker, sector and period
sizing      Position sizing (fractional Kelly, volatility targeting, ERC)
simulate    Deterministic synthetic market/trade generation (fixed seeds, fixed dates)
demo        End-to-end demo on the committed sample data (python -m trademetrics.demo)

No module in this package connects to a broker. All committed data is synthetic,
generated by tools/make_sample_data.py.
"""

__version__ = "1.0.0"
