"""End-to-end demo on the committed sample data.

Run from the repo root:

    python -m trademetrics.demo

Loads data/samples/*.csv (synthetic, generated by tools/make_sample_data.py),
prints the full analytics summary, and writes outputs/results.json — the single
source the dashboard is built from. The sample data is fixed and every
computation is deterministic, so the output is identical on every run.
"""

import json
from pathlib import Path

import pandas as pd

from trademetrics.attribution import AttributionEngine
from trademetrics.benchmark import BenchmarkAnalysis
from trademetrics.fifo import FifoEngine
from trademetrics.loaders import load_benchmarks, load_nav, load_trades
from trademetrics.metrics import MetricsEngine
from trademetrics.simulate import SAMPLE_MARKET
from trademetrics.sizing import PositionSizer

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data" / "samples"
OUTPUTS_DIR = REPO_ROOT / "outputs"

# The synthetic market is simulated under this risk-free rate; the engine must
# use the same one for CAPM alpha to be interpretable (see simulate.py).
RF = SAMPLE_MARKET["rf_ann"]

SECTOR_MAP = {
    "NVDA": "Semiconductors",
    "AMD": "Semiconductors",
    "MSFT": "Software",
    "ORCL": "Software",
    "CRM": "Software",
    "PLTR": "Software",
    "META": "Consumer Internet",
    "GOOGL": "Consumer Internet",
    "AMZN": "Consumer Internet",
    "TSLA": "Consumer Tech",
    "SPY": "Index Hedge",
}


def run_demo(data_dir: Path = DATA_DIR) -> dict:
    """Run the full pipeline on the sample CSVs and return the results payload."""
    nav = load_nav(data_dir / "nav_sample.csv")
    trades = load_trades(data_dir / "trades_sample.csv")
    bench_prices = load_benchmarks(data_dir / "benchmarks_sample.csv")

    fifo = FifoEngine(trades)
    realised = fifo.realised_pnl()
    open_pos = fifo.open_positions()

    engine = MetricsEngine(nav, realised_pnl=realised, rf=RF)
    summary = engine.summary()

    bench = BenchmarkAnalysis(engine.returns, bench_prices, rf=RF)
    bench_summary = bench.summary()

    attrib = AttributionEngine(realised, nav, sector_map=SECTOR_MAP)
    monthly = attrib.returns_by_period("ME")

    sizer = PositionSizer(nav=float(nav.iloc[-1]))
    sizing_example = sizer.recommended_size(
        ticker="NVDA", ticker_vol=0.38, win_rate=0.60, avg_win=0.20, avg_loss=0.10
    )

    indexed = bench.cumulative_indexed()
    dd = engine.drawdown_series()

    return {
        "meta": {
            "data": "synthetic sample (data/samples/, generated by tools/make_sample_data.py)",
            "period": f"{nav.index[0].date()} to {nav.index[-1].date()}",
            "rf_ann": RF,
            "generator_seed": SAMPLE_MARKET["seed"],
        },
        "summary": summary,
        "benchmarks": bench_summary.to_dict(orient="records"),
        "series": {
            "dates": [d.strftime("%Y-%m-%d") for d in indexed.index],
            "portfolio_indexed": [round(v, 4) for v in indexed["Portfolio"]],
            "spy_indexed": [round(v, 4) for v in indexed["SPY"]],
            "qqq_indexed": [round(v, 4) for v in indexed["QQQ"]],
            "drawdown": [round(v, 6) for v in dd.reindex(indexed.index).fillna(0.0)],
        },
        "monthly_returns": {
            "labels": [d.strftime("%b %y") for d in monthly.index],
            "portfolio": [round(v, 3) for v in monthly],
        },
        "realised_by_ticker": attrib.pnl_by_ticker().round(2).to_dict(orient="records"),
        "pnl_by_sector": attrib.pnl_by_sector().round(2).to_dict(orient="records"),
        "realised_trades": [
            {
                **{k: (round(v, 2) if isinstance(v, float) else v) for k, v in row.items()},
                "entry_date": row["entry_date"].strftime("%Y-%m-%d"),
                "exit_date": row["exit_date"].strftime("%Y-%m-%d"),
            }
            for row in realised.to_dict(orient="records")
        ],
        "open_positions": [
            {
                **{k: (round(v, 2) if isinstance(v, float) else v) for k, v in row.items()},
                "entry_date": row["entry_date"].strftime("%Y-%m-%d"),
            }
            for row in open_pos.to_dict(orient="records")
        ],
        "sizing_example": sizing_example,
    }


def _fmt_pct(x: float) -> str:
    return f"{x * 100:+.2f}%"


def print_report(results: dict) -> None:
    s = results["summary"]
    print("=" * 64)
    print("  TradeMetrics — engine demo on committed synthetic sample data")
    print(f"  Period {results['meta']['period']}  ·  rf = {RF:.1%} (annualised)")
    print("=" * 64)

    print("\n  Performance")
    print("-" * 44)
    print(f"  Total return            {_fmt_pct(s['total_return'])}")
    print(f"  Annualised return       {_fmt_pct(s['annualised_return'])}")
    print(f"  Annualised volatility   {s['annualised_volatility'] * 100:.2f}%")
    print(
        f"  Sharpe ratio            {s['sharpe']:.2f}"
        f"  (95% CI {s['sharpe_ci_low']:.2f} to {s['sharpe_ci_high']:.2f}, "
        f"Lo SE {s['sharpe_se']:.2f}, n={s['n_obs']})"
    )
    print(f"  Sortino ratio           {s['sortino']:.2f}")
    print(f"  Calmar ratio            {s['calmar']:.2f}")
    print(f"  Max drawdown            {_fmt_pct(s['max_drawdown'])}")

    print("\n  One-day Value at Risk (fraction of NAV)")
    print("-" * 44)
    print(f"  95% parametric          {s['var_95_parametric'] * 100:.2f}%")
    print(f"  95% historical          {s['var_95_historical'] * 100:.2f}%")
    print(f"  99% parametric          {s['var_99_parametric'] * 100:.2f}%")
    print(f"  99% historical          {s['var_99_historical'] * 100:.2f}%")

    print("\n  Benchmark comparison (CAPM, excess-return regression)")
    print("-" * 44)
    for row in results["benchmarks"]:
        print(
            f"  {row['benchmark']:<5} alpha {row['capm_alpha_ann'] * 100:+.2f}%/yr "
            f"(95% CI {row['alpha_ci_low'] * 100:+.2f}% to {row['alpha_ci_high'] * 100:+.2f}%)  "
            f"beta {row['beta']:.2f}  R² {row['r_squared']:.2f}  IR {row['info_ratio']:.2f}"
        )

    print("\n  Realised FIFO P&L (net of commissions)")
    print("-" * 44)
    print(f"  Round-trips             {s['n_round_trips']}")
    print(f"  Win rate                {s['win_rate'] * 100:.1f}%")
    print(f"  Profit factor           {s['profit_factor']:.2f}")
    print(f"  Avg holding period      {s['avg_holding_days']:.1f} days")
    by_ticker = pd.DataFrame(results["realised_by_ticker"])
    print("\n" + by_ticker.to_string(index=False))

    open_pos = pd.DataFrame(results["open_positions"])
    print("\n  Open positions at period end")
    print("-" * 44)
    print(open_pos.to_string(index=False) if not open_pos.empty else "  (none)")

    sz = results["sizing_example"]
    print("\n  Position sizing example (quarter-Kelly vs vol target)")
    print("-" * 44)
    print(f"  Ticker                  {sz['ticker']}")
    print(f"  Kelly fraction (1/4)    {sz['kelly_fraction']:.4f}")
    print(f"  Vol-target fraction     {sz['vol_target']:.4f}")
    print(f"  Recommended             {sz['recommended']:.4f} of NAV")
    print(f"  Allocation              {sz['allocation']:,.2f} USD")

    print("\n  All figures computed from data/samples/*.csv — synthetic data,")
    print("  regenerate with: python tools/make_sample_data.py")


def main() -> None:
    results = run_demo()
    print_report(results)
    OUTPUTS_DIR.mkdir(exist_ok=True)
    out_path = OUTPUTS_DIR / "results.json"
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n  Results written to {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
